"""HANA database client for Knowledge Agent."""

import json
from typing import Any, Optional, List, Dict
from hdbcli import dbapi
from config import get_settings


class HanaClient:
    """HANA database client for storing and retrieving knowledge chunks."""
    
    def __init__(self):
        self.config = get_settings()
        self._conn: Optional[dbapi.Connection] = None
    
    def connect(self) -> None:
        """Establish connection to HANA."""
        self._conn = dbapi.connect(
            address=self.config.hana_host,
            port=self.config.hana_port,
            user=self.config.hana_user,
            password=self.config.hana_password,
            encrypt=True,
            sslValidateCertificate=False,
        )
        cur = self._conn.cursor()
        cur.execute(f'SET SCHEMA "{self.config.hana_schema}"')
        cur.close()
    
    def close(self) -> None:
        if self._conn:
            self._conn.close()
    
    def create_table(self, drop_first: bool = False) -> None:
        """Create knowledge base table if not exists."""
        cur = self._conn.cursor()
        if drop_first:
            try:
                cur.execute(f'DROP TABLE "{self.config.hana_table}"')
                self._conn.commit()
            except Exception:
                self._conn.rollback()
        
        cur.execute(f"""
            CREATE COLUMN TABLE "{self.config.hana_table}" (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                VEC_TEXT NCLOB,
                VEC_META NCLOB,
                VEC_VECTOR REAL_VECTOR({self.config.vector_dimension})
            )
        """)
        self._conn.commit()
        cur.close()
    
    def get_existing_urls(self) -> set[str]:
        """Get all URLs already in the knowledge base."""
        cur = self._conn.cursor()
        urls = set()
        try:
            cur.execute(f'SELECT VEC_META FROM "{self.config.hana_table}"')
            for (meta_str,) in cur.fetchall():
                try:
                    meta = json.loads(meta_str or "{}")
                    if meta.get("url"):
                        urls.add(meta["url"])
                except Exception:
                    pass
        except Exception:
            pass
        cur.close()
        return urls
    
    def insert_chunks(self, chunks: List[Dict[str, Any]]) -> int:
        """Insert text chunks with metadata."""
        if not chunks:
            return 0
        
        cur = self._conn.cursor()
        inserted = 0
        
        for chunk in chunks:
            try:
                cur.execute(
                    f'INSERT INTO "{self.config.hana_table}" (VEC_TEXT, VEC_META) VALUES (?, ?)',
                    (chunk["text"], json.dumps(chunk["meta"])),
                )
                inserted += 1
            except Exception:
                pass
        
        self._conn.commit()
        cur.close()
        return inserted
    
    def get_unvectorized_chunks(self, limit: int = 20) -> List[tuple]:
        """Get chunks without embeddings."""
        cur = self._conn.cursor()
        cur.execute(f"""
            SELECT TOP {limit} ID, VEC_TEXT, VEC_META
            FROM "{self.config.hana_table}"
            WHERE VEC_VECTOR IS NULL
        """)
        rows = cur.fetchall()
        cur.close()
        return rows
    
    def update_embeddings(self, updates: List[tuple]) -> None:
        """Update chunks with embedding vectors."""
        cur = self._conn.cursor()
        for chunk_id, vector in updates:
            vec_str = "[" + ",".join(str(v) for v in vector) + "]"
            cur.execute(f"""
                UPDATE "{self.config.hana_table}"
                SET VEC_VECTOR = TO_REAL_VECTOR('{vec_str}')
                WHERE ID = {chunk_id}
            """)
        self._conn.commit()
        cur.close()
    
    def search_similar(self, query_vector: List[float], top_k: int = 5) -> List[Dict]:
        """Search for similar chunks using cosine similarity."""
        vec_str = "[" + ",".join(str(v) for v in query_vector) + "]"
        
        cur = self._conn.cursor()
        cur.execute(f"""
            SELECT VEC_TEXT, VEC_META,
                   COSINE_SIMILARITY(VEC_VECTOR, TO_REAL_VECTOR('{vec_str}')) as SIMILARITY
            FROM "{self.config.hana_table}"
            WHERE VEC_VECTOR IS NOT NULL
            ORDER BY SIMILARITY DESC
            LIMIT {top_k}
        """)
        
        results = []
        for row in cur.fetchall():
            results.append({
                "text": row[0],
                "meta": json.loads(row[1]),
                "similarity": row[2] * 100,
            })
        
        cur.close()
        return results
    
    def get_stats(self) -> Dict[str, int]:
        """Get table statistics."""
        cur = self._conn.cursor()
        cur.execute(f'SELECT COUNT(*) FROM "{self.config.hana_table}"')
        total = cur.fetchone()[0]
        cur.execute(f'SELECT COUNT(*) FROM "{self.config.hana_table}" WHERE VEC_VECTOR IS NOT NULL')
        vectorized = cur.fetchone()[0]
        cur.close()
        return {"total": total, "vectorized": vectorized, "pending": total - vectorized}
    
    def __enter__(self):
        self.connect()
        return self
    
    def __exit__(self, *args):
        self.close()